<?php

define("EQUUS_HORSES_EXTRAS_REGULAR_HC_TID",1);
// define("EQUUS_HORSES_EXTRAS_RARE_HC_TID",2);
define("EQUUS_HORSES_EXTRAS_POTENTIAL_STAT_MAX", 1000);
define("EQUUS_HORSES_EXTRAS_POTENTIAL_STAT_MIN", 500);
define("EQUUS_HORSES_EXTRAS_CUR_POT_STAT_RATIO", 0.50);

/**
 * Displays an error message if the user has not created 
 * an organization and/or a property when attempting to create a horse.
 *
 * Displays the number of each type of horse credits the user has. 
 *
 * Displays only those properties associated with an organization
 * that the currently logged in user is a member of in the horse 
 * residence field.
 *
 * Implements hook_form_alter for the horse creation form.
 */
function equus_horses_extras_form_horse_node_form_alter(&$form, $form_state) {
	$uid = $GLOBALS['user']->uid;
	// get all organizations (and properties) associated with the currently logged in user
	$properties = equus_properties_get_user_assoc_properties_by_org($uid);

	// if the user has no organizations, print an error
	if (empty($properties)) {
		drupal_set_message('You need to create an organization and a property before you can create a horse.','error');
	} else {
		$empty = TRUE;

		// if the user has no properties, print an error
		foreach ($properties as $property_list) {
			if (!empty($property_list)) {
				$empty = FALSE;
				break;
			}
		}

		if ($empty) {
			drupal_set_message('You need to create a property before you can create a horse.','error');
		}
	}
	
	// pass the correct property options to the form for the horse residence field
	$form['field_horse_residence']['und']['#options'] = $properties;

    // pass the correct organization options to the form for the creating organization field
    $organizations = equus_organizations_get_org_options($uid);
    $form['field_horse_creating_org']['und']['#options'] = $organizations;

	$current_regular_HC = userpoints_get_current_points($uid, EQUUS_HORSES_EXTRAS_REGULAR_HC_TID);

	$message = "";
	$status = "";
	if ($current_regular_HC == 0) {
		$message .= "You have 0 Horse Credits ";
		$status .= "warning";
	} else if ($current_regular_HC == 1) {
		$message .= "You have 1 Horse Credit ";
		$status .= "status";
	} else if ($current_regular_HC > 1) {
		$message .= "You have $current_regular_HC Horse Credits ";
		$status .= "status";
	}
	drupal_set_message($message, $status);

    $is_new = $form['nid']['#value'] === NULL;
    $is_active = false;
    $is_foal = true;

    // If the horse is being edited, disable the creating org field. Creating org should only be accessible on first creation.
    if (!$is_new) {
        $horse = node_load($form['nid']['#value']);
		$form['field_horse_creating_org']['#access'] = false;

        if ($horse->field_horse_activation_status[LANGUAGE_NONE][0]['value'] == 'Active') {
            $is_active = true;
            $form['field_horse_activation_status']['#access'] = false;
        }
	}

	$breed_IDs = array_slice(array_keys($form['field_horse_breed']['und']['#options']),1);

	$breeds = node_load_multiple($breed_IDs);

	foreach ($breeds as $breed) {
		$form['field_horse_breed']['und']['#options'][$breed->nid] = $breed->field_base_breed['und'][0]['value'] . " - " . $breed->title;
	}

	asort($form['field_horse_breed']['und']['#options']);
    
	$form['temp_age'] = array(
	    '#type' => 'textfield',
	    '#title' => 'Age',
	    '#description' => 'Enter an age to automatically update the Date of Birth field, or change the date of birth to have the age automatically calculated.',
	    '#required' => false,
	    '#size' => 3,
	    '#weight' => 21,
	);

    if (!$is_active) {
    	$form['temp_age']['#states'] = array(
            'enabled' => array(
                'input[name="aging_system_unlock"]' => array(
                    'checked' => true,
                )
            )
    	);
    } else {
    	$form['temp_age']['#disabled'] = true;
	}

	$form['field_horse_date_of_birth'][LANGUAGE_NONE][0]['#element_validate'] = array('equus_horses_extras_dob_validation');
	if (!$is_active) {
	    $form['field_horse_date_of_birth']['#states'] = array(
	        'enabled' => array(
	            'input[name="aging_system_unlock"]' => array(
	                'checked' => true,
	            )
	        )
	    );
    } else {
		$form['field_horse_date_of_birth']['#disabled'] = true;
	}

	if (!$is_new) {
		$form['aging_system_unlock'] = array(
	        '#type' => 'checkbox',
	        '#title' => 'Unlock aging system?',
	        '#description' => 'Checking this box will unlock the fields related to the aging system for this horse. Changes will be saved when the horse is saved.',
	        '#required' => false,
	        '#attributes' => array(
	            'onclick' => "equusHorsesExtrasToggleAgingSystem();",
	        )
	    );
	    $form['#group_children']['aging_system_unlock'] = 'group_horse_aging';
	}

	$form['field_horse_rp_age']['#states'] = array(
		'enabled' => array(
            'input[name="aging_system_unlock"]' => array(
                'checked' => true,
            )
        )
	);

    // add programmatically created aging related fields to the general group on the horse node
    $form['#group_children']['temp_age'] = 'group_horse_aging';

    // hide horse stats field from users
    $form['field_horse_stats']['#access'] = 0;

//    $form['#attached']['js'] = array(
//        drupal_get_path('module', 'equus_horses_extras') . '/equus_horses_extras.js',
//    );
}

function equus_horses_extras_dob_validation($element, &$form_state) {

}

/**
 * Gets the user's associated horses (active and inactive)
 *
 * @param $uid The ID of the user in question.
 * @param $only_active True if only want activated horses. False by default.
 * @return An array of horse IDs. Will return empty array if there are no assoc horses.
 */
function equus_horses_extras_get_assoc_horses($uid, $only_active = false) {
		// get user's associated properties
	$nids = equus_properties_get_user_assoc_properties($uid);
	if (empty($nids)) {
		// if nids is empty return an empty array
		return array();
	}

	//query for all horses associated with a property
	$query = new EntityFieldQuery();
	$query
		->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'horse')
		->propertyCondition('status', 1)
		->fieldCondition('field_horse_residence', 'target_id', $nids, 'IN');

    if ($only_active) {
        $query->fieldCondition('field_horse_activation_status', 'value', 'Active', '=');
    }

	$result = $query->execute();

	$horses = array();

	if (count($result) > 0) {
		$horses = array_keys($result['node']);
	}
	return $horses;
}

/**
 * Gets the horses that are in residence at a property.
 *
 * @param $nid The id of the property.
 * @return array An array of horse IDs in residence at the property.
 * 				 Will return empty array if there are no assoc horses.
 */
function equus_horses_extras_get_prop_assoc_horses($nid) {
	$query = new EntityFieldQuery();
	$query
		->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'horse')
		->propertyCondition('status', 1)
		->fieldCondition('field_horse_residence', 'target_id', $nid, '=');
	$result = $query->execute();

	$horses = array();

	if (count($result) > 0) {
		$horses = array_keys($result['node']);
	}
	return $horses;
}

/**
 *	Gets the org which owns the property the horse resides at
 * 
 * @param $horse Horse node.
 * @return Organization node or null.
 */
function equus_horses_extras_get_residence_org($horse) {
	$residence_id = $horse->field_horse_residence[LANGUAGE_NONE][0]['target_id'];

	$residence = node_load($residence_id);
	if (!$residence) {
		return NULL;
	}

	$org_ID = $residence->field_property_ownership[LANGUAGE_NONE][0]['target_id'];

	$org = node_load($org_ID);
	if (!$org_ID) {
		return NULL;
	}
	return $org;
}

/**
 * Gets a list of horse options by name.
 * @param $nids IDs of the horses 
 */
function equus_horses_extras_get_horse_options($nids) {
	if (empty($nids)) {
		return;
	}

	$horses = node_load_multiple($nids);

	// populate the array that we are going to use to set the options
	$horse_options = array();
	foreach ($horses as $horse) {
		$horse_options[$horse->nid] = $horse->field_horse_real_name['und'][0]['value'];
	}
	return $horse_options;
}

/**
 * Verifies that the user has at least 1 HC in order to activate a horse.
 * @param $uid ID of the currently logged in user.
 */
function equus_horses_extras_validate_regular_hc_count($uid) {
	$current_regular_HC = userpoints_get_current_points($uid, EQUUS_HORSES_EXTRAS_REGULAR_HC_TID);
	if ($current_regular_HC < 1 ) {
		form_set_error('field_horse_activation_status', 'You do not have enough Horse Credits to make this horse active. Please visit the Store to buy a Horse Credit.');
	}
}

/**
 * Verifies that the currently logged in user is a member of the 
 * organization that the property in question belongs to.
 * @param $uid ID of the currently logged in user
 * @param $nid ID of the property in question
 */
function equus_horses_extras_validate_residence_ownshp($uid, $nid) {
	$organizations = equus_properties_get_user_assoc_properties_by_org($uid);

	$found = FALSE;
	foreach ($organizations as $properties) {
		foreach ($properties as $propertyid => $property) {
			if ($propertyid == $nid) {
				$found = TRUE;
				break;
			}
		}
		if ($found) {
			break;
		}
	}
	if (!$found) {
		form_set_error('field_horse_residence', "You must be a member of the organization that owns the residence property to assign a horse to it.");
	}
}

/**
 * Performs validation on horse creation form elements.
 * 
 * Implements hook_node_validate
 */
function equus_horses_extras_node_validate($node, $form, &$form_state) {
	if ($node->type != 'horse') {
		return;
	}

	// Verify that user has enough horse credits to activate the horse
	// TODO: Make this section its own function
	// check if new horse
	if (!isset($node->nid)) {
		// if new check whether active is set
		if ($node->field_horse_activation_status['und'][0]['value'] == 'Active') {
			// if yes check for points
			equus_horses_extras_validate_regular_hc_count($form['uid']['#value']);
		} 
	} else {
		// get activation status
		$original_value = $form['#node']->field_horse_activation_status['und'][0]['value'];
		$new_value = $node->field_horse_activation_status['und'][0]['value'];

		// if not new check whether previous value is pending and new value is active
		if ($original_value == 'Pending' && $new_value == 'Active') {
			// if yes check for points
			equus_horses_extras_validate_regular_hc_count($form['uid']['#value']);
		}
	}

	// Verify that residence/property is owned by the currently logged in user
	equus_horses_extras_validate_residence_ownshp($form['uid']['#value'], $node->field_horse_residence['und'][0]['target_id']);

	// Verify that existing horse hasn't had its creating org changed
/*	if ($node->nid != NULL) {
		$original_creating_org = $form['#node']->field_horse_creating_org['und'][0]['target_id'];
		$new_creating_org = $node->field_horse_creating_org['und'][0]['target_id'];
		// If the horse is being edited, disable the creating org field. Creating org should only be accessible on first creation.
		if ($original_creating_org != $new_creating_org) {
			form_set_error('field_horse_creating_org', "Database consistency error. Please contact the site administrator.");
			watchdog('field_horse_creating_org', 'Attempted to change creating org after horse was already created. uid = @uid', array('@uid'=>$node->uid), WATCHDOG_ERROR);
		}
	}*/
	// TODO: Test whether the field permissions module handles this for me already: 
	// Are there any fields that are critical to gameplay and would be game breaking if people were able to freely edit?
	// Stats
	// Gender
	// Age
	// Pedigree
	// Show Cooldown
	// TODO: Ask Peter about doing this in a loop
}

function equus_horses_extras_node_submit($node, $form, &$form_state) {
    if ($node->type != 'horse') {
        return;
    }

    if ($node->field_horse_activation_status[LANGUAGE_NONE][0]['value'] == 'Active') {
        $is_active = true;
    } else {
    	$is_active = false;
    }
}

function equus_horses_extras_node_presave($node) {
	if ($node->type != 'horse') {
		return;
	}
	if ($node->nid == NULL || $node->original->title != $node->title) {
		$orgID = $node->field_horse_creating_org['und'][0]['target_id'];
		$org = node_load($orgID);
		$real_name = equus_organizations_calc_real_name($node->title, $org);
		$node->field_horse_real_name['und'][0]['value'] = $real_name;
	}

    // assign stats to horse if activation status changes from pending to active
    if (isset($node->original->field_horse_activation_status['und'][0]['value'])) {
        $original_value = $node->original->field_horse_activation_status['und'][0]['value'];
    } else {
        $original_value = false;
    }
    $new_value = $node->field_horse_activation_status['und'][0]['value'];

    // if not new check whether previous value is pending and new value is active
    if ((!$original_value || $original_value == 'Pending') && $new_value == 'Active') {
        // spend a horse credit to activate the horse
        $status = equus_horses_extras_spend_regular_hc($node->uid);

        // if we failed to spend a horse credit
        if ($status === false) {
            // reset activation status
            $node->field_horse_activation_status['und'][0]['value'] = 'Pending';
            watchdog('equus_horses_extras', 'Attempted to spend HC but didn\'t have enough. uid = @uid', array('@uid'=>$node->uid), WATCHDOG_ERROR);
            drupal_set_message("Not enough horse credits to activate a horse. Activating a horse costs one horse credit. You can buy one in the store!", 'error');
        } else {
            // assign stats
            $node->field_horse_stats[LANGUAGE_NONE][0]['value'] = equus_horses_extras_calc_stats($node);
        }
    }
}

/**
 * Detracts a regular HC from a user's account
 * @param $uid ID of the user to detract a regular HC from.
 */
function equus_horses_extras_spend_regular_hc($uid) {
	$current_regular_HC = userpoints_get_current_points($uid, EQUUS_HORSES_EXTRAS_REGULAR_HC_TID);
	if ($current_regular_HC < 1 ) {
		return false;
	}
	userpoints_userpointsapi(array(
		'uid' => $uid,
		'points' => -1,
		'tid' => EQUUS_HORSES_EXTRAS_REGULAR_HC_TID
	));
	return true;
}

/**
 * Adds some number of regular HCs to a user's account
 * @param $uid ID of the user to give regular HC to.
 * @param $quantity Number of regular HC to give a user.
 */
function equus_horses_extras_gain_regular_hc($uid, $quantity) {
	userpoints_userpointsapi(array(
		'uid' => $uid,
		'points' => $quantity,
		'tid' => EQUUS_HORSES_EXTRAS_REGULAR_HC_TID
	));
}

/**
 *	Calculates the horse's initial stats based on breed and body type
 *
 * -- SHOULD ONLY BE USED UPON INITIAL STAT DISTRIBUTION FOR FOUNDATIONS--
 *
 * @param $nid Node ID of the horse
 */
function equus_horses_extras_calc_stats($horse) {
	$breedID = $horse->field_horse_breed[LANGUAGE_NONE][0]['target_id'];
	$breed_stats = equus_horses_extras_get_breed_stats($breedID);

	$body_typeID = $horse->field_horse_body_type[LANGUAGE_NONE][0]['target_id'];
	$modifiers = equus_horses_extras_get_body_type_modifiers($body_typeID);

	$stats = array_keys(list_allowed_values(field_info_field('field_stat')));

    $potential_sum = 0;
    $raw_potentials = array();
	foreach ($stats as $stat) {
        $low_potential = $breed_stats[$stat]['low'] + $modifiers[$stat];
        $high_potential = $breed_stats[$stat]['high'] + $modifiers[$stat];

        if ($low_potential < 0) {
            $low_potential = 0;
        }
        if ($high_potential > 100) {
            $high_potential = 100;
        }
        $raw_potential = rand($low_potential, $high_potential);
        $potential_sum += $raw_potential;

        $raw_potentials[$stat] = $raw_potential;
    }

    $dob = $horse->field_horse_date_of_birth[LANGUAGE_NONE][0]['value'];
    $age = equus_horses_extras_calc_age($dob);
    $target = equus_horses_extras_calc_current_stat_target($age);
    $target = $target / 100;
    $indiv_potential_max = rand(EQUUS_HORSES_EXTRAS_POTENTIAL_STAT_MIN, EQUUS_HORSES_EXTRAS_POTENTIAL_STAT_MAX);
    $scale_factor = $indiv_potential_max / $potential_sum;
    $stats_field = array();
    foreach ($raw_potentials as $stat => $raw_potential) {
        $indiv_potential = $raw_potential * $scale_factor;

        // potential * ratio * age scale
		$current = round($indiv_potential * EQUUS_HORSES_EXTRAS_CUR_POT_STAT_RATIO * $target);

        $stats_field[$stat] = array(
            'current' => $current,
            'potential' => $indiv_potential,
            'highest_trained' => $current
        );
	}
    return json_encode($stats_field);
}

function equus_horses_extras_get_breed_stats($breedID) {
	$breed = node_load($breedID);
	// get horse stats
	$stats = $breed->field_breed_stat_windows[LANGUAGE_NONE];
	$result = array();
	foreach ($stats as $stat) {
		$field_collection_item = field_collection_item_load($stat['value']);
		
		$stat_name = $field_collection_item->field_stat['und'][0]['value'];
		
		$stat_low_value = $field_collection_item->field_breed_low_stat_value['und'][0]['value'];

		$stat_high_value = $field_collection_item->field_breed_high_stat_value['und'][0]['value'];

		$result[$stat_name] = array('low' => $stat_low_value, 'high' => $stat_high_value);
	}
	return $result;
}

function equus_horses_extras_get_body_type_modifiers($body_typeID) {
	$body_type = node_load($body_typeID);
	// get horse stats
	$stats = $body_type->field_body_type_stat_modifier[LANGUAGE_NONE];
	$result = array();
	foreach ($stats as $stat) {
		$field_collection_item = field_collection_item_load($stat['value']);
		
		$stat_name = $field_collection_item->field_stat['und'][0]['value'];
		
		$stat_modifier = $field_collection_item->field_stat_modifier['und'][0]['value'];

		$result[$stat_name] = $stat_modifier;
	}
	return $result;
}

function computed_field_field_horse_age_compute(&$entity_field, $entity_type, $entity, $field) {
	$dob = field_get_items($entity_type, $entity, 'field_horse_date_of_birth');
    $computed_age = equus_horses_extras_calc_age($dob[0]['value']);
    // if ($computed_age < 1) {
    // 	$age = "< 1";
    // } else {
    // 	$age = $computed_age;
    // }

	$entity_field[0]['value'] = $computed_age;
}

/**
 * Calculates the age of a horse in game days based on information about the aging
 * speed at various time periods in its life.
 *
 * @param Array $aging_details Array of time period objects to consider. Each time period
 *                           should have properties start (string:Y-m-d H:i:s),
 *                           end (string:Y-m-d H:i:s), and speed (Integer).
 * @param string $today The day to calculate the age against, defaults to today
 * @return int Number of game days old the horse is
 */
function equus_horses_extras_calc_age($dob) {
    if (empty($dob)) {
        return NULL;
    }

    // foal speed = 1 months to 1 year
    $foal_speed = 12;
    // adult speed = 4 months to 1 year
    $adult_speed = 3;
    // transition age = 4
    $transition_year = 4;
    $dob_calcd = new DateTime($dob);
    $today = new DateTime('now');
    $real_days = (int) $today->diff($dob_calcd)->format('%a');
    $transition_year = floatval($transition_year);
    $transition_days = $transition_year * 365;

    $game_days_tentative = $real_days * $foal_speed;
    if ($game_days_tentative < $transition_days) {
        return floor($game_days_tentative / 365);
    } else {
        $real_days_foal = $transition_days / $foal_speed;
        $real_days_adult = $real_days - $real_days_foal;
        return floor($transition_year + ($real_days_adult * $adult_speed) / 365);
    }
}

function equus_horses_extras_calc_current_stat_target($age) {
    if ($age >= 0 && $age < 5) {
        return round(2 * ($age * $age));
    } else if ($age >= 5 && $age < 10) {
        return round(100 - 2 * (pow(10 - $age, 2)));
    } else {
        return 100;
    }
}

function equus_horses_extras_theme() {
    return array(
        'equus_horses_extras_aging_history' => array(
            'variables' => array(),
            'template' => 'equus_horses_extras_aging_history',
        ),
    );
}
