<?php 
/**
 * Implements hook_entity_info_alter().
 */

function equus_members_entity_info_alter(&$entity_info) {
	$entity_info['user']['view modes']['about'] = array(
		'label' => t('About Me'),
		'custom settings' => TRUE,
	);

	$entity_info['user']['view modes']['chibi_about'] = array(
		'label' => t('Chibi About'),
		'custom settings' => TRUE,
	);
}

function equus_members_get_net_worth($uid) {
	$ledger = equus_banking_retrieve_ledger();
	$nids = equus_organizations_get_assoc_orgs($uid);
	
	$total = array_reduce($nids, function($carry, $item) use (&$ledger) {
		return $carry + equus_banking_balance($ledger, $item);
	}, 0);

	setlocale(LC_MONETARY, 'en_US');
	return money_format('%.0n', $total);
}

/*function equus_members_gallery_image_count($uid) {
	$query = new EntityFieldQuery();
	$query
		->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'gallery_image')
		->propertyCondition('status', 1)
		->propertyCondition('uid', $uid);
	$result = $query->execute();
	return count($result['node']);
}*/

function equus_members_horse_count($uid) {
	$query = new EntityFieldQuery();
	$query
		->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'horse')
		->propertyCondition('status', 1)
		->propertyCondition('uid', $uid);
	$result = $query->execute();
	return count($result['node']);
}

function equus_members_preprocess_user_profile(&$vars) {
	$vars['theme_hook_suggestions'][] = 'user_profile__' . $vars['elements']['#view_mode'];

	$items = field_get_items('user', $vars['elements']['#account'], 'field_user_dob');
	$date = array_pop($items);
	
	$dob = new DateTime($date['value']);
	$interval = $dob->diff(new DateTime());
	$vars['age'] = $interval->y;
	
	$vars['net_worth'] = equus_members_get_net_worth($vars['elements']['#account']->uid);

	$items = field_get_items('user', $vars['elements']['#account'], 'field_user_gender');
	$vars['user_gender'] = $items[0]['value'];

	$items = field_get_items('user', $vars['elements']['#account'], 'field_user_biography');
	$vars['user_biography'] = $items[0]['value'];

	//$vars['gallery_count'] = equus_members_gallery_image_count($vars['elements']['#account']->uid);
	$vars['horse_count'] = equus_members_horse_count($vars['elements']['#account']->uid);
	//$vars['user_like_count'] = flag_get_user_flags('node'), $vars['elements']['#account']->uid);
}

function equus_members_preprocess_equus_stats(&$vars) {
	$url = explode('/',$_GET['q']);
	$uid = $url[1];

	$vars['stats'][] = array('value'=>equus_members_get_net_worth($uid));
}

