<?php 
/**
 * Implements hook_entity_info_alter().
 */

function equus_core_entity_info_alter(&$entity_info) {
	$entity_info['node']['view modes']['tiles'] = array(
		'label' => t('Tiles'),
		'custom settings' => TRUE,
	);

	$entity_info['node']['view modes']['thumbnail'] = array(
		'label' => t('Thumbnails'),
		'custom settings' => TRUE,
	);
}

function equus_core_block_info() {
	$blocks = array();

	$blocks['stats'] = array(
		'info' => t('Stats'),
		'region' => 'sidebar_first',
		'visibility' => BLOCK_VISIBILITY_LISTED,
		'pages' => 'user/*/profile'
	);

	$blocks['footer_logo'] = array(
		'info' => t('Footer Logo'),
	);
	
	return $blocks;
}

function equus_core_block_view($delta='') {
	$block = array();

	switch($delta) {
		case 'stats':
			$vars = array('stats' => array());
			$block['title'] = "Stats";
			$block['content'] = theme('equus_stats', $vars);
			break;
		case 'footer_logo':
			$vars = array('footer_logo' => array());
			$block['content'] = theme('equus_footer_logo', $vars);
			break;
	}

	return $block;
}

function equus_core_theme() {
	return array(
		'equus_stats' => array(
			'variables' => array(),
			'template' => 'equus_stats',
		),
		'equus_footer_logo' => array(
			'variables' => array(),
			'template' => 'equus_footer_logo',
		),
	);
}